// This file is automatically generated. Please do not edit by hand.

#ifndef __EMTF_HLSLIB_PATTERN_BANK_H__
#define __EMTF_HLSLIB_PATTERN_BANK_H__

namespace emtf_hlslib {

  namespace phase2 {

    namespace detail {

      // clang-format off

constexpr static const int pattern_col_reference = 55;
constexpr static const int pattern_col_max_pad = 36;

constexpr static const int pattern_col_start_zone_0_patt_0[8] = {51, 51, 52, 54, 54, 54, 54, 54};
constexpr static const int pattern_col_start_zone_0_patt_1[8] = {43, 43, 46, 53, 54, 55, 55, 55};
constexpr static const int pattern_col_start_zone_0_patt_2[8] = {57, 57, 56, 54, 54, 53, 53, 52};
constexpr static const int pattern_col_start_zone_0_patt_3[8] = {35, 35, 39, 53, 54, 54, 54, 52};
constexpr static const int pattern_col_start_zone_0_patt_4[8] = {61, 62, 59, 54, 54, 51, 50, 49};
constexpr static const int pattern_col_start_zone_0_patt_5[8] = {21, 21, 27, 51, 54, 51, 50, 44};
constexpr static const int pattern_col_start_zone_0_patt_6[8] = {65, 67, 62, 54, 54, 48, 47, 45};
constexpr static const int pattern_col_start_zone_1_patt_0[8] = {50, 51, 53, 54, 54, 54, 54, 54};
constexpr static const int pattern_col_start_zone_1_patt_1[8] = {38, 41, 48, 53, 54, 55, 55, 54};
constexpr static const int pattern_col_start_zone_1_patt_2[8] = {59, 58, 55, 54, 54, 53, 53, 53};
constexpr static const int pattern_col_start_zone_1_patt_3[8] = {26, 30, 44, 53, 54, 52, 51, 47};
constexpr static const int pattern_col_start_zone_1_patt_4[8] = {67, 64, 57, 54, 54, 52, 51, 51};
constexpr static const int pattern_col_start_zone_1_patt_5[8] = {19, 19, 39, 52, 54, 43, 38, 28};
constexpr static const int pattern_col_start_zone_1_patt_6[8] = {71, 69, 56, 53, 54, 52, 52, 53};
constexpr static const int pattern_col_start_zone_2_patt_0[8] = {53, 53, 54, 54, 54, 54, 54, 54};
constexpr static const int pattern_col_start_zone_2_patt_1[8] = {50, 50, 53, 54, 54, 54, 54, 54};
constexpr static const int pattern_col_start_zone_2_patt_2[8] = {55, 55, 54, 54, 54, 53, 54, 53};
constexpr static const int pattern_col_start_zone_2_patt_3[8] = {47, 48, 53, 54, 52, 51, 49, 48};
constexpr static const int pattern_col_start_zone_2_patt_4[8] = {57, 56, 54, 54, 53, 53, 53, 52};
constexpr static const int pattern_col_start_zone_2_patt_5[8] = {43, 44, 53, 54, 46, 40, 37, 32};
constexpr static const int pattern_col_start_zone_2_patt_6[8] = {56, 55, 53, 54, 52, 52, 52, 52};

constexpr static const int pattern_col_mid_zone_0_patt_0[8]   = {55, 55, 55, 55, 55, 55, 55, 55};
constexpr static const int pattern_col_mid_zone_0_patt_1[8]   = {49, 49, 50, 55, 55, 56, 56, 56};
constexpr static const int pattern_col_mid_zone_0_patt_2[8]   = {61, 61, 60, 55, 55, 54, 54, 54};
constexpr static const int pattern_col_mid_zone_0_patt_3[8]   = {42, 42, 45, 54, 55, 57, 57, 57};
constexpr static const int pattern_col_mid_zone_0_patt_4[8]   = {68, 68, 65, 56, 55, 53, 53, 53};
constexpr static const int pattern_col_mid_zone_0_patt_5[8]   = {33, 32, 38, 54, 55, 56, 56, 54};
constexpr static const int pattern_col_mid_zone_0_patt_6[8]   = {77, 78, 72, 56, 55, 54, 54, 56};
constexpr static const int pattern_col_mid_zone_1_patt_0[8]   = {55, 55, 55, 55, 55, 55, 55, 55};
constexpr static const int pattern_col_mid_zone_1_patt_1[8]   = {46, 47, 52, 55, 55, 56, 56, 56};
constexpr static const int pattern_col_mid_zone_1_patt_2[8]   = {64, 63, 58, 55, 55, 54, 54, 54};
constexpr static const int pattern_col_mid_zone_1_patt_3[8]   = {35, 38, 49, 54, 55, 55, 55, 53};
constexpr static const int pattern_col_mid_zone_1_patt_4[8]   = {75, 72, 61, 56, 55, 55, 55, 57};
constexpr static const int pattern_col_mid_zone_1_patt_5[8]   = {25, 30, 48, 55, 55, 51, 47, 42};
constexpr static const int pattern_col_mid_zone_1_patt_6[8]   = {85, 80, 62, 55, 55, 59, 63, 68};
constexpr static const int pattern_col_mid_zone_2_patt_0[8]   = {55, 55, 55, 55, 55, 55, 55, 55};
constexpr static const int pattern_col_mid_zone_2_patt_1[8]   = {52, 53, 55, 55, 55, 55, 55, 55};
constexpr static const int pattern_col_mid_zone_2_patt_2[8]   = {58, 57, 55, 55, 55, 55, 55, 55};
constexpr static const int pattern_col_mid_zone_2_patt_3[8]   = {50, 51, 54, 55, 55, 54, 54, 53};
constexpr static const int pattern_col_mid_zone_2_patt_4[8]   = {60, 59, 56, 55, 55, 56, 56, 57};
constexpr static const int pattern_col_mid_zone_2_patt_5[8]   = {48, 49, 55, 55, 53, 49, 48, 45};
constexpr static const int pattern_col_mid_zone_2_patt_6[8]   = {62, 61, 55, 55, 57, 61, 62, 65};

constexpr static const int pattern_col_stop_zone_0_patt_0[8]  = {59, 59, 58, 56, 56, 56, 56, 56};
constexpr static const int pattern_col_stop_zone_0_patt_1[8]  = {53, 53, 54, 56, 56, 57, 57, 58};
constexpr static const int pattern_col_stop_zone_0_patt_2[8]  = {67, 67, 64, 57, 56, 55, 55, 55};
constexpr static const int pattern_col_stop_zone_0_patt_3[8]  = {49, 48, 51, 56, 56, 59, 60, 61};
constexpr static const int pattern_col_stop_zone_0_patt_4[8]  = {75, 75, 71, 57, 56, 56, 56, 58};
constexpr static const int pattern_col_stop_zone_0_patt_5[8]  = {45, 43, 48, 56, 56, 62, 63, 65};
constexpr static const int pattern_col_stop_zone_0_patt_6[8]  = {89, 89, 83, 59, 56, 59, 60, 66};
constexpr static const int pattern_col_stop_zone_1_patt_0[8]  = {60, 59, 57, 56, 56, 56, 56, 56};
constexpr static const int pattern_col_stop_zone_1_patt_1[8]  = {51, 52, 55, 56, 56, 57, 57, 57};
constexpr static const int pattern_col_stop_zone_1_patt_2[8]  = {72, 69, 62, 57, 56, 55, 55, 56};
constexpr static const int pattern_col_stop_zone_1_patt_3[8]  = {43, 46, 53, 56, 56, 58, 59, 59};
constexpr static const int pattern_col_stop_zone_1_patt_4[8]  = {84, 80, 66, 57, 56, 58, 59, 63};
constexpr static const int pattern_col_stop_zone_1_patt_5[8]  = {39, 41, 54, 57, 56, 58, 58, 57};
constexpr static const int pattern_col_stop_zone_1_patt_6[8]  = {91, 91, 71, 58, 56, 67, 72, 82};
constexpr static const int pattern_col_stop_zone_2_patt_0[8]  = {57, 57, 56, 56, 56, 56, 56, 56};
constexpr static const int pattern_col_stop_zone_2_patt_1[8]  = {55, 55, 56, 56, 56, 57, 56, 57};
constexpr static const int pattern_col_stop_zone_2_patt_2[8]  = {60, 60, 57, 56, 56, 56, 56, 56};
constexpr static const int pattern_col_stop_zone_2_patt_3[8]  = {53, 54, 56, 56, 57, 57, 57, 58};
constexpr static const int pattern_col_stop_zone_2_patt_4[8]  = {63, 62, 57, 56, 58, 59, 61, 62};
constexpr static const int pattern_col_stop_zone_2_patt_5[8]  = {54, 55, 57, 56, 58, 58, 58, 58};
constexpr static const int pattern_col_stop_zone_2_patt_6[8]  = {67, 66, 57, 56, 64, 70, 73, 78};

constexpr static const int pattern_col_pad_zone_0[8]          = {34, 34, 28,  4,  1,  7,  8, 11};
constexpr static const int pattern_col_pad_zone_1[8]          = {36, 36, 16,  3,  1, 12, 17, 27};
constexpr static const int pattern_col_pad_zone_2[8]          = {12, 11,  2,  1,  9, 15, 18, 23};

constexpr static const int pattern_activation_zone_0[1u << 8] = {
  0,  0,  0,  3,  0, 28,  8, 22,  0, 42,  5,  7, 12, 40, 18, 25,  0,  9,  5,  8,  6, 32, 16, 33,
 16, 32, 14, 20, 18, 34, 26, 35,  0, 10,  5, 10,  3, 16,  6, 12,  4, 38, 11, 15,  6, 35, 12, 30,
  4, 10, 11, 14, 10, 37, 13, 36, 19, 36,  7, 21, 20, 48, 36, 48,  0, 55,  3,  4,  2, 39,  8, 16,
 24, 57, 12, 11, 19, 52, 23, 27, 25, 34, 15, 17,  8, 49, 17, 44, 33, 52, 18, 26, 26, 51, 34, 49,
 15, 26,  6,  9,  4, 21,  7, 19, 27, 52, 13, 22, 20, 48, 31, 39, 30, 31,  9, 24, 17, 47, 29, 43,
 38, 47, 27, 37, 29, 56, 49, 53,  0, 38,  2,  3,  2, 23, 14, 23, 17, 56, 13, 18, 14, 49, 28, 44,
 21, 41, 11, 39,  9, 58, 29, 58, 29, 56, 28, 43, 31, 57, 46, 57, 25, 27, 19, 21,  7, 40, 28, 47,
 30, 55, 35, 46, 32, 56, 46, 60, 38, 44, 22, 43, 35, 59, 47, 59, 45, 54, 42, 53, 48, 63, 57, 63,
 24, 54,  5, 15, 13, 43, 22, 37, 33, 62, 23, 34, 31, 58, 45, 53, 37, 52, 24, 45, 30, 60, 42, 59,
 44, 61, 39, 51, 41, 61, 54, 61, 40, 46, 20, 32, 25, 50, 36, 51, 40, 60, 41, 54, 42, 60, 55, 62,
 45, 51, 33, 50, 41, 62, 55, 61, 50, 59, 50, 58, 53, 63, 62, 63
};


constexpr static const int pattern_activation_zone_1[1u << 8] = {
  0,  0,  0, 10,  0,  2,  4,  7,  0,  9, 15, 27, 37,  3,  4,  6,  0, 16, 21, 36, 48,  9,  5, 11,
 24, 25, 31, 46, 47,  9, 16, 30,  0,  3,  5, 20, 28, 36, 23, 42,  8, 14, 24, 51, 15,  7, 10, 14,
  6, 21, 17, 50, 26, 19,  7, 37, 16, 29, 34, 57, 30,  8, 12, 31,  0,  2,  4, 13, 33, 18,  7, 19,
 12, 12, 18, 33, 29,  4, 12, 17, 28, 19, 20, 40, 45, 17, 11, 32, 30, 32, 38, 54, 42, 22, 30, 45,
 10,  5,  8, 24, 38, 40, 33, 54, 14, 20, 28, 46, 25,  6, 10, 18, 15, 27, 31, 55, 35, 24, 21, 39,
 26, 36, 42, 58, 39, 13, 22, 41,  0,  3,  3, 13, 37, 34, 23, 44,  2,  6, 15, 38, 13, 18,  5, 29,
 14, 23, 26, 52, 42, 38, 33, 51, 26, 41, 49, 61, 41, 35, 45, 59, 35, 22, 22, 46, 57, 58, 54, 61,
 20, 39, 49, 60, 16, 11, 25, 55, 28, 47, 49, 60, 50, 50, 48, 60, 36, 51, 56, 63, 40, 32, 45, 59,
 34,  8,  9, 25, 53, 51, 43, 56, 11, 19, 29, 50, 27, 17, 23, 46, 37, 40, 44, 58, 52, 43, 41, 57,
 44, 53, 57, 63, 52, 47, 53, 62, 47, 31, 35, 49, 61, 61, 59, 63, 21, 39, 48, 60, 27, 32, 44, 58,
 34, 52, 54, 62, 56, 55, 55, 62, 43, 56, 59, 63, 48, 43, 53, 62
};


constexpr static const int pattern_activation_zone_2[1u << 8] = {
  0,  0,  0,  9,  0, 29, 32, 41,  0, 16, 16, 34, 14, 32, 33, 43,  0,  5,  4, 12,  7, 15, 15, 28,
 38, 36, 38, 49, 12, 33, 24, 44,  0,  8,  5, 14, 18, 26, 30, 41, 11, 16, 22, 35, 29, 36, 39, 48,
  3, 10,  8, 22, 13, 31, 20, 42, 20, 31, 28, 45, 25, 46, 43, 54,  0,  5,  4,  7,  8, 11, 21, 32,
 24, 26, 22, 41, 17, 49, 30, 52, 17, 18, 19, 33, 23, 37, 32, 53, 58, 54, 50, 59, 44, 57, 53, 62,
  3,  9,  6, 20, 21, 23, 21, 41, 34, 39, 36, 53, 35, 51, 47, 59, 19, 27, 15, 47, 31, 50, 43, 58,
 59, 58, 51, 62, 52, 60, 59, 63,  0,  3,  2,  4,  8, 19, 12, 26,  6, 13, 10, 27, 17, 27, 25, 40,
  5,  6,  6, 23, 19, 30, 24, 44, 17, 35, 36, 47, 30, 46, 42, 55,  2, 10,  4, 13, 15, 25, 18, 38,
 10, 18, 24, 38, 31, 39, 40, 51,  3, 16, 11, 26, 27, 45, 37, 53, 25, 46, 45, 54, 47, 56, 54, 60,
  2,  9,  7, 12, 14, 29, 23, 40, 20, 43, 34, 49, 28, 48, 39, 55, 11, 35, 13, 42, 37, 50, 42, 57,
 55, 58, 48, 62, 49, 60, 56, 63,  7, 14,  9, 28, 29, 40, 34, 50, 33, 48, 44, 57, 45, 55, 52, 61,
 22, 37, 21, 51, 46, 57, 52, 61, 60, 61, 56, 63, 56, 62, 61, 63
};

      // clang-format on

    }  // namespace detail

  }  // namespace phase2

}  // namespace emtf_hlslib

#endif  // __EMTF_HLSLIB_PATTERN_BANK_H__ not defined
