// This file is automatically generated. Please do not edit by hand.

#ifndef __EMTF_HLSLIB_PATTERN_BANK_H__
#define __EMTF_HLSLIB_PATTERN_BANK_H__

namespace emtf_hlslib {

  namespace phase2 {

    namespace detail {

      // clang-format off

constexpr static const int pattern_col_reference = 55;
constexpr static const int pattern_col_max_pad = 36;

constexpr static const int pattern_col_start_zone_0_patt_0[8] = {51, 51, 52, 54, 54, 54, 54, 54};
constexpr static const int pattern_col_start_zone_0_patt_1[8] = {43, 43, 46, 53, 54, 55, 55, 55};
constexpr static const int pattern_col_start_zone_0_patt_2[8] = {57, 57, 56, 54, 54, 53, 53, 53};
constexpr static const int pattern_col_start_zone_0_patt_3[8] = {34, 35, 39, 53, 54, 54, 54, 53};
constexpr static const int pattern_col_start_zone_0_patt_4[8] = {61, 62, 59, 54, 54, 51, 50, 49};
constexpr static const int pattern_col_start_zone_0_patt_5[8] = {21, 23, 29, 52, 54, 52, 50, 46};
constexpr static const int pattern_col_start_zone_0_patt_6[8] = {65, 67, 62, 54, 54, 48, 47, 45};
constexpr static const int pattern_col_start_zone_1_patt_0[8] = {50, 51, 53, 54, 54, 54, 54, 54};
constexpr static const int pattern_col_start_zone_1_patt_1[8] = {39, 41, 48, 53, 54, 55, 55, 54};
constexpr static const int pattern_col_start_zone_1_patt_2[8] = {59, 58, 55, 54, 54, 53, 53, 53};
constexpr static const int pattern_col_start_zone_1_patt_3[8] = {27, 30, 44, 53, 54, 52, 51, 47};
constexpr static const int pattern_col_start_zone_1_patt_4[8] = {66, 64, 57, 54, 54, 52, 51, 51};
constexpr static const int pattern_col_start_zone_1_patt_5[8] = {19, 19, 41, 52, 54, 41, 34, 23};
constexpr static const int pattern_col_start_zone_1_patt_6[8] = {71, 68, 57, 53, 54, 51, 51, 52};
constexpr static const int pattern_col_start_zone_2_patt_0[8] = {53, 53, 54, 54, 54, 54, 54, 54};
constexpr static const int pattern_col_start_zone_2_patt_1[8] = {50, 50, 53, 54, 54, 54, 54, 54};
constexpr static const int pattern_col_start_zone_2_patt_2[8] = {55, 55, 54, 54, 54, 53, 54, 53};
constexpr static const int pattern_col_start_zone_2_patt_3[8] = {47, 48, 53, 54, 52, 51, 49, 48};
constexpr static const int pattern_col_start_zone_2_patt_4[8] = {57, 56, 54, 54, 53, 53, 53, 52};
constexpr static const int pattern_col_start_zone_2_patt_5[8] = {43, 45, 52, 54, 46, 40, 37, 31};
constexpr static const int pattern_col_start_zone_2_patt_6[8] = {57, 56, 53, 54, 53, 52, 52, 52};

constexpr static const int pattern_col_mid_zone_0_patt_0[8]   = {55, 55, 55, 55, 55, 55, 55, 55};
constexpr static const int pattern_col_mid_zone_0_patt_1[8]   = {49, 49, 50, 55, 55, 56, 56, 56};
constexpr static const int pattern_col_mid_zone_0_patt_2[8]   = {61, 61, 60, 55, 55, 54, 54, 54};
constexpr static const int pattern_col_mid_zone_0_patt_3[8]   = {42, 42, 45, 54, 55, 57, 57, 57};
constexpr static const int pattern_col_mid_zone_0_patt_4[8]   = {68, 68, 65, 56, 55, 53, 53, 53};
constexpr static const int pattern_col_mid_zone_0_patt_5[8]   = {33, 33, 39, 54, 55, 57, 56, 55};
constexpr static const int pattern_col_mid_zone_0_patt_6[8]   = {77, 77, 71, 56, 55, 53, 54, 55};
constexpr static const int pattern_col_mid_zone_1_patt_0[8]   = {55, 55, 55, 55, 55, 55, 55, 55};
constexpr static const int pattern_col_mid_zone_1_patt_1[8]   = {46, 47, 52, 55, 55, 56, 56, 56};
constexpr static const int pattern_col_mid_zone_1_patt_2[8]   = {64, 63, 58, 55, 55, 54, 54, 54};
constexpr static const int pattern_col_mid_zone_1_patt_3[8]   = {35, 39, 49, 54, 55, 55, 55, 53};
constexpr static const int pattern_col_mid_zone_1_patt_4[8]   = {75, 71, 61, 56, 55, 55, 55, 57};
constexpr static const int pattern_col_mid_zone_1_patt_5[8]   = {28, 31, 47, 55, 55, 50, 45, 40};
constexpr static const int pattern_col_mid_zone_1_patt_6[8]   = {82, 79, 63, 55, 55, 60, 65, 70};
constexpr static const int pattern_col_mid_zone_2_patt_0[8]   = {55, 55, 55, 55, 55, 55, 55, 55};
constexpr static const int pattern_col_mid_zone_2_patt_1[8]   = {52, 53, 55, 55, 55, 55, 55, 55};
constexpr static const int pattern_col_mid_zone_2_patt_2[8]   = {58, 57, 55, 55, 55, 55, 55, 55};
constexpr static const int pattern_col_mid_zone_2_patt_3[8]   = {50, 51, 54, 55, 55, 54, 54, 53};
constexpr static const int pattern_col_mid_zone_2_patt_4[8]   = {60, 59, 56, 55, 55, 56, 56, 57};
constexpr static const int pattern_col_mid_zone_2_patt_5[8]   = {48, 49, 55, 55, 53, 49, 48, 45};
constexpr static const int pattern_col_mid_zone_2_patt_6[8]   = {62, 61, 55, 55, 57, 61, 62, 65};

constexpr static const int pattern_col_stop_zone_0_patt_0[8]  = {59, 59, 58, 56, 56, 56, 56, 56};
constexpr static const int pattern_col_stop_zone_0_patt_1[8]  = {53, 53, 54, 56, 56, 57, 57, 57};
constexpr static const int pattern_col_stop_zone_0_patt_2[8]  = {67, 67, 64, 57, 56, 55, 55, 55};
constexpr static const int pattern_col_stop_zone_0_patt_3[8]  = {49, 48, 51, 56, 56, 59, 60, 61};
constexpr static const int pattern_col_stop_zone_0_patt_4[8]  = {76, 75, 71, 57, 56, 56, 56, 57};
constexpr static const int pattern_col_stop_zone_0_patt_5[8]  = {45, 43, 48, 56, 56, 62, 63, 65};
constexpr static const int pattern_col_stop_zone_0_patt_6[8]  = {89, 87, 81, 58, 56, 58, 60, 64};
constexpr static const int pattern_col_stop_zone_1_patt_0[8]  = {60, 59, 57, 56, 56, 56, 56, 56};
constexpr static const int pattern_col_stop_zone_1_patt_1[8]  = {51, 52, 55, 56, 56, 57, 57, 57};
constexpr static const int pattern_col_stop_zone_1_patt_2[8]  = {71, 69, 62, 57, 56, 55, 55, 56};
constexpr static const int pattern_col_stop_zone_1_patt_3[8]  = {44, 46, 53, 56, 56, 58, 59, 59};
constexpr static const int pattern_col_stop_zone_1_patt_4[8]  = {83, 80, 66, 57, 56, 58, 59, 63};
constexpr static const int pattern_col_stop_zone_1_patt_5[8]  = {39, 42, 53, 57, 56, 59, 59, 58};
constexpr static const int pattern_col_stop_zone_1_patt_6[8]  = {91, 91, 69, 58, 56, 69, 76, 87};
constexpr static const int pattern_col_stop_zone_2_patt_0[8]  = {57, 57, 56, 56, 56, 56, 56, 56};
constexpr static const int pattern_col_stop_zone_2_patt_1[8]  = {55, 55, 56, 56, 56, 57, 56, 57};
constexpr static const int pattern_col_stop_zone_2_patt_2[8]  = {60, 60, 57, 56, 56, 56, 56, 56};
constexpr static const int pattern_col_stop_zone_2_patt_3[8]  = {53, 54, 56, 56, 57, 57, 57, 58};
constexpr static const int pattern_col_stop_zone_2_patt_4[8]  = {63, 62, 57, 56, 58, 59, 61, 62};
constexpr static const int pattern_col_stop_zone_2_patt_5[8]  = {53, 54, 57, 56, 57, 58, 58, 58};
constexpr static const int pattern_col_stop_zone_2_patt_6[8]  = {67, 65, 58, 56, 64, 70, 73, 79};

constexpr static const int pattern_col_pad_zone_0[8]          = {34, 32, 26,  3,  1,  7,  8, 10};
constexpr static const int pattern_col_pad_zone_1[8]          = {36, 36, 14,  3,  1, 14, 21, 32};
constexpr static const int pattern_col_pad_zone_2[8]          = {12, 10,  3,  1,  9, 15, 18, 24};

constexpr static const int pattern_activation_zone_0[1u << 8] = {
  0, 18, 14, 26,  7, 33, 26, 38,  3, 39, 20, 45, 10, 49, 36, 54,  1, 19, 15, 27,  9, 34, 30, 43,
  5, 41, 22, 46, 12, 51, 38, 55,  0, 18, 14, 27,  8, 33, 28, 38,  4, 41, 22, 45, 11, 50, 37, 54,
  2, 20, 16, 29,  9, 34, 32, 46,  6, 41, 24, 47, 14, 52, 47, 57,  0, 18, 14, 27,  8, 35, 28, 43,
  4, 40, 21, 45, 11, 53, 37, 56,  2, 20, 15, 29, 10, 37, 31, 49,  5, 44, 23, 48, 13, 56, 40, 58,
  1, 19, 15, 27,  9, 35, 30, 43,  5, 42, 23, 46, 12, 54, 39, 57,  2, 21, 17, 30, 11, 44, 36, 53,
  6, 45, 25, 50, 22, 58, 52, 60,  0, 19, 15, 28,  8, 34, 29, 40,  4, 41, 22, 46, 11, 51, 37, 55,
  2, 21, 16, 31, 10, 49, 32, 55,  6, 44, 24, 48, 13, 57, 42, 59,  1, 20, 16, 30,  8, 34, 31, 44,
  5, 43, 24, 48, 12, 52, 40, 58,  3, 24, 18, 33, 13, 58, 39, 60,  7, 49, 32, 53, 26, 61, 56, 62,
  1, 19, 16, 29,  9, 36, 31, 47,  4, 42, 23, 47, 12, 57, 38, 59,  3, 25, 17, 35, 13, 59, 36, 61,
  7, 54, 25, 56, 28, 62, 51, 63,  3, 23, 17, 32, 10, 48, 33, 55,  6, 50, 25, 52, 21, 60, 50, 62,
  7, 39, 26, 51, 35, 62, 59, 63, 17, 60, 42, 61, 53, 63, 61, 63
};


constexpr static const int pattern_activation_zone_1[1u << 8] = {
  0,  2, 24, 29,  0,  2, 24, 29,  3,  7, 31, 38,  4,  8, 31, 39, 10, 13, 38, 45, 10, 14, 38, 46,
 17, 20, 48, 53, 17, 20, 49, 53,  0,  2, 25, 31,  6,  7, 26, 33,  4,  8, 31, 40,  7, 11, 32, 42,
 10, 14, 39, 48, 13, 16, 40, 49, 18, 21, 50, 55, 19, 23, 50, 55,  0,  2, 25, 30,  1,  3, 25, 30,
  4,  8, 32, 41,  5,  9, 33, 41, 11, 15, 40, 47, 11, 15, 41, 47, 19, 23, 51, 55, 20, 23, 51, 56,
  1,  3, 27, 34, 12, 15, 28, 36,  5,  9, 34, 43, 14, 18, 36, 45, 12, 16, 43, 51, 19, 22, 44, 52,
 21, 28, 52, 58, 26, 29, 53, 59,  1,  3, 25, 30,  7,  9, 27, 35,  5,  8, 32, 40,  9, 13, 33, 42,
 11, 14, 39, 47, 16, 18, 41, 49, 18, 22, 50, 57, 21, 26, 50, 57,  5,  6, 27, 37, 37, 42, 46, 54,
  6, 12, 34, 47, 38, 43, 48, 55, 13, 19, 44, 56, 42, 45, 52, 60, 21, 28, 52, 61, 44, 48, 56, 62,
  1,  4, 26, 33, 22, 24, 35, 39,  6, 10, 34, 44, 23, 27, 36, 49, 12, 17, 43, 53, 28, 30, 46, 54,
 24, 35, 54, 62, 35, 37, 56, 63, 15, 17, 32, 45, 57, 58, 59, 61, 16, 20, 37, 54, 57, 59, 59, 62,
 22, 29, 51, 61, 58, 60, 61, 63, 36, 46, 60, 63, 58, 60, 62, 63
};


constexpr static const int pattern_activation_zone_2[1u << 8] = {
  0, 11, 24, 43,  4, 20, 30, 52,  1, 13, 26, 45,  8, 22, 35, 55,  0, 11, 25, 43,  5, 20, 31, 53,
  3, 14, 27, 46, 10, 24, 37, 56,  3, 15, 29, 47,  9, 28, 39, 57,  4, 17, 30, 48, 14, 35, 42, 59,
  3, 16, 30, 48, 10, 29, 40, 58,  7, 19, 32, 51, 19, 40, 43, 61,  0, 11, 25, 43,  4, 20, 31, 52,
  2, 13, 26, 45,  8, 23, 36, 56,  0, 12, 25, 44,  6, 21, 33, 54, 15, 23, 34, 51, 34, 46, 46, 61,
  3, 16, 29, 47, 10, 28, 40, 58,  5, 18, 31, 51, 17, 39, 42, 61,  4, 17, 30, 49, 12, 37, 41, 60,
 23, 39, 41, 59, 48, 59, 58, 63,  1, 11, 25, 44,  6, 20, 33, 53,  2, 13, 27, 45,  9, 24, 37, 55,
  1, 12, 26, 45,  7, 22, 34, 54,  5, 16, 28, 47, 14, 32, 39, 57,  5, 16, 31, 49, 13, 35, 41, 59,
  7, 18, 33, 50, 19, 40, 44, 60,  6, 18, 32, 50, 17, 38, 42, 60,  9, 22, 36, 54, 24, 51, 52, 62,
  1, 12, 26, 44,  7, 21, 33, 53,  2, 15, 27, 47, 10, 29, 38, 56,  2, 14, 27, 46,  9, 28, 36, 56,
 19, 36, 38, 57, 41, 57, 54, 63,  6, 18, 32, 49, 15, 37, 42, 60,  8, 22, 35, 55, 23, 49, 50, 62,
  8, 21, 34, 53, 21, 50, 48, 62, 38, 55, 52, 62, 58, 63, 61, 63
};

      // clang-format on

    }  // namespace detail

  }  // namespace phase2

}  // namespace emtf_hlslib

#endif  // __EMTF_HLSLIB_PATTERN_BANK_H__ not defined
